openapi: 3.0.0
info:
  title: fake sms app
  description: Fake nika Api
  version: 0.1.9

servers:
  - url: https://employee-companies-api.nika-nozadze.redberryinternship.ge/api
    description: production server
  - url: http://localhost:3000/api
    description: local server  

paths:
  /sms:
    post:
      tags:
        - Fake sms 
      requestBody:
        description: funny for people
        required: true
        content:
          application/json:
            schema: 
              type: object
                properties:
                  to: 
                    type: string
                  text: 
                    type: string
      responses:
        '200':
          description: sms sent  
  